### ISSUE TITLE
GitShark iOS Checklist

### ISSUE THREAD

**Issue by crutchcorn** [oceanbit-dev/GitShark#58]
This is a non-comprehensive checklist for things I need to do for the iOS alpha release:

- [ ] Fix branch loading
- [ ] Test/verify GitHub login works
- [ ] Test/verify committing works
- [ ] Port Git Log command to native code binding
- [ ] Port `revList` to native code binding
- [ ] Port `status` to native code binding
